version: "3"
services:
  app:
    image: calling-agent
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.calling-agent.rule=Host(`calling-agent.abubakarkhalid.com`)"
      - "traefik.http.routers.calling-agent.entrypoints=websecure"
      - "traefik.http.routers.calling-agent.tls=true"
      - "traefik.http.routers.calling-agent.tls.certresolver=myresolver"
    networks:
      - traefik
networks:
  traefik:
    external: true
