version: "3"
services:
  app:
    context: . # This tells Docker Compose to use the Dockerfile in the current directory
    dockerfile: Dockerfile # Optional if your file is named "Dockerfile"
    image: ghcr.io/muhammadahmad1857/marketing-agents-ghcr:latest # Name of the built image
    container_name: calling-agent-container
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.calling-agent.rule=Host(calling-agent.kognifi.ai)"
      - "traefik.http.routers.calling-agent.entrypoints=websecure"
      - "traefik.http.services.calling-agent.loadbalancer.server.port=8007"
      - "traefik.http.routers.calling-agent.tls=true"
      - "traefik.http.routers.calling-agent.tls.certresolver=myresolver"
    networks:
      - traefik
    pull_policy: always
    command: ["npm", "start"]

networks:
  traefik:
    external: true
